name: Build and Deploy

on:
  push:
    branches: main

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install Project Dependencies
        run: npm ci

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@5.8.0

      - name: Build
        run: gatsby build

      - name: Verify build
        run: ls -la public

      # - name: 📂 Deploy files
      #   uses: easingthemes/ssh-deploy@main
      #   with:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     SOURCE: "public/"
      #     REMOTE_HOST: ${{ secrets.FTP_ADDRESS }}
      #     REMOTE_USER: ${{ secrets.FTP_USERNAME }}
      #     TARGET: "httpdocs/"
